# This file was generated by GoReleaser. DO NOT EDIT.
class Proji < Formula
  desc "A powerful cross-platform CLI project templating tool."
  homepage "https://github.com/nikoksr/proji"
  version "0.20.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/nikoksr/proji/releases/download/v0.20.0/proji_Darwin_64bit.tar.gz"
    sha256 "137a694c2df327b6f2a0bc6e09fe6b3a33adf0bce0730a7e6046448ab573fe4e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/nikoksr/proji/releases/download/v0.20.0/proji_Linux_64bit.tar.gz"
      sha256 "69645642d69b756afa05ba22960bdc894ebc11cfc6ea4e6be17ba0187641efe0"
    end
  end

  def install
    bin.install "proji"
  end
end
