# This file was generated by GoReleaser. DO NOT EDIT.
class Proji < Formula
  desc "A powerful cross-platform CLI project templating tool."
  homepage "https://github.com/nikoksr/proji"
  version "0.19.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/nikoksr/proji/releases/download/v0.19.1/proji-macOS-64bit.tar.gz"
    sha256 "bd4a4c013720d056084bf7b3c634160ac429bdde897bb41ee91eb3057170a2d7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/nikoksr/proji/releases/download/v0.19.1/proji-Linux-64bit.tar.gz"
      sha256 "d0c4b700be01f030a5b49b3ad5099faed7fd005fbf32bf83e47c7431dcbecced"
    end
  end

  def install
    bin.install "proji"
  end
end
